### ISSUE TITLE
Issue with wlan_key.ino

### ISSUE THREAD

**Issue by vipit** [samratashok/Kautilya#10]
Hi,

Thanks for your toolset, it is very helpfull. When I tried to copy some of the wlan_key.ino code into a .ps1 file for testing, I noticed errors due to the following sentence:

"  Keyboard.println("echo $w = netsh wlan show profiles ^| sls -Pattern \"All User Profile\" ^| foreach {$_.ToString()} >> %temp%\\wl.ps1"); "

The error was "The term 'sls' is not recognized as the name of a cmdlet, function, script file, or operable program."

It seems that "sls" is unknown on the system I tested it on. It is a basic Win7 system with all current updates. I changed 'sls' to 'Select-String' and then it worked for me.

**Comment by samratashok** [comment]
Thanks for reporting this. You must be using PowerShellv2. sls as alias of Select-String is not defined in v2. I have replaced all the occurences of sls with Select-String to avoid this problem in future.
