### ISSUE TITLE
expected ')' before ';' token

### ISSUE THREAD

**Issue by ners11** [samratashok/Kautilya#13]
Hi everyone!
I need your help. Please tell me what I doing wrong. I have an error when I trying upload (check the code) to the teensy. Code generated by Kautilya. 
Regards.

![2015-05-15 22 39 06](https://cloud.githubusercontent.com/assets/12465264/7660521/74aba74e-fb53-11e4-89dd-2c136f05c38f.png)

**Comment by samratashok** [comment]
Same as Issue #12
