### ISSUE TITLE
Error when compiling with Arduino IDE

### ISSUE THREAD

**Issue by vpetrache** [samratashok/Kautilya#15]
Hei,

I'm trying to upload code for credentials.ino and I have some struggles.
Any idea why I get compilation errors below?

Thanks in advance,

Arduino: 1.6.7 (Windows 8.1), TD: 1.27, Board: "Teensy 2.0, Keyboard + Mouse + Joystick, 16 MHz, US English"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -hardware "C:\Users\vpetrache\AppData\Local\Arduino15\packages" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -tools "C:\Users\vpetrache\AppData\Local\Arduino15\packages" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\vpetrache\Documents\Arduino\libraries" -fqbn=teensy:avr:teensy2:usb=hid,speed=16,keys=en-us -ide-version=10607 -build-path "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino"
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -hardware "C:\Users\vpetrache\AppData\Local\Arduino15\packages" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -tools "C:\Users\vpetrache\AppData\Local\Arduino15\packages" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\vpetrache\Documents\Arduino\libraries" -fqbn=teensy:avr:teensy2:usb=hid,speed=16,keys=en-us -ide-version=10607 -build-path "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/../avr/bin/avr-g++" -E -CC -x c++ -w  -g -Wall -ffunction-sections -fdata-sections -fno-exceptions -felide-constructors -std=c++0x -mmcu=atmega32u4 -DTEENSYDUINO=127 -DARDUINO=10607 -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DUSB_HID -DLAYOUT_US_ENGLISH "-IC:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy" "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\sketch\credentials.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/../avr/bin/avr-g++" -E -CC -x c++ -w  -g -Wall -ffunction-sections -fdata-sections -fno-exceptions -felide-constructors -std=c++0x -mmcu=atmega32u4 -DTEENSYDUINO=127 -DARDUINO=10607 -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DUSB_HID -DLAYOUT_US_ENGLISH "-IC:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy" "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\sketch\credentials.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/../avr/bin/avr-g++" -E -CC -x c++ -w  -g -Wall -ffunction-sections -fdata-sections -fno-exceptions -felide-constructors -std=c++0x -mmcu=atmega32u4 -DTEENSYDUINO=127 -DARDUINO=10607 -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DUSB_HID -DLAYOUT_US_ENGLISH "-IC:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy" "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\sketch\credentials.ino.cpp" -o "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino5/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/../avr/bin/avr-g++" -c -Os -g -Wall -ffunction-sections -fdata-sections -MMD -fno-exceptions -felide-constructors -std=c++0x -mmcu=atmega32u4 -DTEENSYDUINO=127 -DARDUINO=10607 -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DUSB_HID -DLAYOUT_US_ENGLISH "-IC:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy" "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\sketch\credentials.ino.cpp" -o "C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\sketch\credentials.ino.cpp.o"
In file included from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy/usb_api.h:4:0,
from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy/WProgram.h:22,
from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy/Arduino.h:1,
from C:\Users\VPETRA~1\AppData\Local\Temp\build22ea799d41487c028ca504b22fecaa1e.tmp\sketch\credentials.ino.cpp:1:
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy/../usb_hid/usb_api.h:75:16: error: previous declaration of 'uint8_t joystick_report_data [12]' with 'C++' linkage
extern uint8_t joystick_report_data[12];
^
In file included from C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy/usb_private.h:4:0,
from C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:3:
C:\Program Files (x86)\Arduino\hardware\teensy\avr\cores\teensy/../usb_hid/usb_private.h:130:39: error: conflicts with new declaration with 'C' linkage
extern uint8_t joystick_report_data[12];
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'void setup()':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:41:19: warning: comparison with string literal results in unspecified behaviour [-Waddress]
if ("gmail" == "pastebin")
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:45:23: warning: comparison with string literal results in unspecified behaviour [-Waddress]
else if ("gmail" == "gmail")
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:56:23: warning: comparison with string literal results in unspecified behaviour [-Waddress]
else if ("gmail" == "post")
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:60:23: warning: comparison with string literal results in unspecified behaviour [-Waddress]
else if ("gmail" == "dns")
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'void wait_for_drivers(int)':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:82:32: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_CAPS_LOCK);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:91:32: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_CAPS_LOCK);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'bool cmd_admin(int, int)':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:109:44: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:116:39: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_modifier(MODIFIERKEY_CTRL);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:118:59: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_modifier(MODIFIERKEY_CTRL | MODIFIERKEY_SHIFT);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:120:28: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_ENTER);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:132:1: warning: no return statement in function returning non-void [-Wreturn-type]
}
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'bool cmd(int, int, char*)':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:138:44: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:139:24: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_R);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:148:28: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_ENTER);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:157:1: warning: no return statement in function returning non-void [-Wreturn-type]
}
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'void make_sure_capslock_is_off()':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:164:32: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_CAPS_LOCK);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'bool check_for_capslock_success_teensy(int, int)':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:198:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
while (!is_caps_on() && (i<reps));
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'void minimise_windows()':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:204:44: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_modifier(MODIFIERKEY_RIGHT_GUI);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:205:24: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_M);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino: In function 'void send_left_enter()':
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:228:29: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_LEFT);
^
C:\Users\vpetrache\Downloads\Kautilya-master\output\credentials\credentials.ino:234:30: warning: large integer implicitly truncated to unsigned type [-Woverflow]
Keyboard.set_key1(KEY_ENTER);
^
exit status 1
Error compiling.

**Comment by samratashok** [comment]
Could you please check with an older version of Arduino IDE? See this https://github.com/samratashok/Kautilya/issues/12

**Comment by samratashok** [comment]
Closing because no response received.
