### ISSUE TITLE
Add support for Digispark

### ISSUE THREAD

**Issue by Akasurde** [samratashok/Kautilya#18]
As title suggest, Could you please add support for Digispark? I tried this code on Digispark but no luck.

I think there is something to do with Keyboard library used in your code.

**Comment by samratashok** [comment]
No plans of adding support for Digispark right now. Sorry!

**Comment by Akasurde** [comment]
@samratashok Hi Do you know how to extend Digispark Keyboard for receiving CapsLock/NumLock status ?

**Comment by samratashok** [comment]
I was stuck at the same point when I gave up on Digispark because of this and size restrictions. 
https://digistump.com/board/index.php?topic=968.0
