### ISSUE TITLE
cannot start kautilya.

### ISSUE THREAD

**Issue by tzionlevy** [samratashok/Kautilya#19]
hi, 
I installed ruby on windows 7 and tried to start the kautilya by the command
ruby kautilya.rb
and i get this error:

```
 C:\Users\Zion\Downloads\Kautilya-master\Kautilya-master>ruby kautilya.rb
C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require':
no such file to load -- bundler/setup (LoadError)
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:i
n `require'
        from kautilya.rb:3:in `<main>'
```

please help.

thanks in advance.

**Comment by NovaHowl** [comment]
Having the same issue.

**Comment by samratashok** [comment]
I just removed the dependency on Win32/Console gem. Update your Kautilya, Run "bundle installer" from Kautilya directory and you should be fine.

**Comment by NovaHowl** [comment]
'Bundle Installer?'

**Comment by samratashok** [comment]
"bundle install"

**Comment by NovaHowl** [comment]
Is that a file or a command on the command line? Because there is no 'Bundle Install' in the main directory.

**Comment by samratashok** [comment]
That's a command. You may need to run "gem install bundler" first and then "bundle install" from Kautilya's root directory.

**Comment by NovaHowl** [comment]
When I try to run that command it throws an error telling me 'certificate verify failed'

gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by NovaHowl** [comment]
@samratashok

**Comment by NovaHowl** [comment]
Tried it on my mac and worked flawlessly. Nevermind.

**Comment by samratashok** [comment]
Looks like you have a local proxy?

**Comment by samratashok** [comment]
Good.

**Comment by Everick** [comment]
Hi,

I am also trying to run kautilya. The following errors show up:
C:/Ruby23/lib/ruby/gems/2.3.0/gems/win32console-1.3.2-x86-mingw32/lib/Win32/Cons
ole.rb:12:in `require': cannot load such file -- 2.3/Console_ext (LoadError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console.rb:12:in `rescue in <top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console.rb:8:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console/ANSI.rb:13:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/win32console-1.3.2-x86-mingw32/l
ib/Win32/Console/ANSI.rb:13:in `<top (required)>'
        from kautilya.rb:5:in `require'
        from kautilya.rb:5:in `<main>'

Do you have any recommendations on what to do next? Thanks in advance.

**Comment by samratashok** [comment]
Please try following commands:
"gem install bundler"
"bundle install"

**Comment by Everick** [comment]
The same errors still occur.

**Comment by samratashok** [comment]
Ok, Try with the latest version of Kautilya. There were some fixes which were recently pushed,

**Comment by Everick** [comment]
Okay it works now. Thank you so very much for your help.

**Comment by samratashok** [comment]
Great!
