### ISSUE TITLE
Powershell script

### ISSUE THREAD

**Issue by sudo23x** [samratashok/Kautilya#20]
I tried the exe to text powershell script but it doesn't seem to work or maybe I am doing something wrong.
Can you explain the steps about how to execute the "Download and Execute" payload.
Thanks you.

**Comment by JBKennedyiii85** [comment]
Not a clue barely any programing knowledge i forked it from someone else i believe

On Mar 11, 2017 2:55 PM, sudo23x <notifications@github.com> wrote:

I tried the exe to text powershell script but it doesn't seem to work or maybe I am doing something wrong.
Can you explain the steps about how to execute the "Download and Execute" payload.
Thanks you.

**Comment by samratashok** [comment]
You can use the exetotxt.ps1 to generate a txt representation of an exe. For example:
PS C:\Kautilya\extras> . .\exetotext.ps1
PS C:\Kautilya\extras> ExetoText -EXE C:\wINDOWS\System32\calc.exe -Filename C:\Kautilya\extras\calc.txt

Now, you must host the generated txt on a webserver and provide Kautilya the url to the hosted txt while generating the payload. It works fine.

**Comment by sudo23x** [comment]
If I use ".\exetotext..." nothing happens but when I don't use ".\" it say ExetoText is not a command

**Comment by samratashok** [comment]
Please note the space between the dots. Its called dot-sourcing for running a PowerShell script which loads a method in current PowerShell sessiom - A dot, followed by space, followed by path to the PowerShell script.
PS C:\Kautilya\extras> . C:\Kautilya\extras\exetotxt.ps1

**Comment by sudo23x** [comment]
It worked now :)
Awesome work btw. Thank.you

**Comment by samratashok** [comment]
Nice! Glad that you got it working!

**Comment by randomusername1337** [comment]
Are there any such file hosting sites where you don't have to provide personal information?
Does kautilya recognize only direct download links?

**Comment by samratashok** [comment]
You may like to try ghostbin or you can use your owen webserver. Yes Kautilya needs direct download links.
