### ISSUE TITLE
reason behind the name of the project

### ISSUE THREAD

**Issue by hashb** [samratashok/Kautilya#23]
Hi Samrat, I am curious to know why this project is called kautilya

**Comment by samratashok** [comment]
Named after Chanakya :)

**Comment by hashb** [comment]
yes, but why the name for a tool like this?

Is it because Kautilya was a ruthless minister?

**Comment by samratashok** [comment]
Because he was also a master warfare strategist :)

**Comment by hashb** [comment]
Awesome, thanks for the reply. My name is Kautilya that's why I was curious. I'm closing the issue now.
